version: '3.8'

services:
  app:
    build: .
    container_name: ai-staff-dev-agent
    volumes:
      - ./test_reports:/app/test_reports
      - ./private/config/backups:/app/private/config/backups
    environment:
      - ENVIRONMENT=production
      - LOG_LEVEL=INFO
    ports:
      - "8000:8000"
    healthcheck:
      test: ["CMD", "python", "-c", "import sys, requests; sys.exit(0 if requests.get('http://localhost:8000/health').status_code == 200 else 1)"]
      interval: 30s
      timeout: 30s
      retries: 3
      start_period: 5s
    restart: unless-stopped

  monitoring:
    image: prom/prometheus:latest
    container_name: monitoring
    volumes:
      - ./monitoring/prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"
    depends_on:
      - app

  dashboard:
    image: grafana/grafana:latest
    container_name: dashboard
    volumes:
      - ./monitoring/grafana/provisioning:/etc/grafana/provisioning
      - ./monitoring/grafana/dashboards:/var/lib/grafana/dashboards
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
      - GF_USERS_ALLOW_SIGN_UP=false
    ports:
      - "3000:3000"
    depends_on:
      - monitoring

networks:
  default:
    name: ai-staff-dev-network
    driver: bridge
