- capabilities:
  - project_generation
  - code_generation
  environment:
    DEVELOPMENT_MODE: 'true'
    PYTHON_VERSION: '3.9'
    TEMPLATE_PATH: private/templates
  name: DevAgent
  parameters:
    default_language: python
    max_concurrent_projects: 5
    test_coverage_requirement: 80
  security_level: high
  version: 1.0.0
- capabilities:
  - base_development
  - development_tasks
  - code_generation
  environment:
    PYTHON_VERSION: '3.9'
    TESTING_MODE: 'true'
    TEST_TEMPLATE_PATH: private/templates/tests
  name: TestAgent
  parameters:
    max_test_runtime: 300
    test_coverage_threshold: 90
  security_level: medium
  version: 1.0.0
